// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5329.ProperRobot.subsystems;

import org.usfirst.frc5329.ProperRobot.RobotMap;
import org.usfirst.frc5329.ProperRobot.commands.*;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drivetrain extends Subsystem {

    private  SpeedController frontLeftSpeedCon;
    private  SpeedController backLeftSpeedCon;
    private  SpeedController frontRightSpeedCon;
    private  SpeedController backRightSpeedCon;
    private  RobotDrive robotDrive41;
    private  Encoder leftEncoder;
    private  Encoder rightEncoder;
    
	private final double k_updatePeriod = 0.005; // update every 0.005 seconds/5 milliseconds (200Hz)

    public Drivetrain(RobotMap robotMap) {
    	this.frontLeftSpeedCon = robotMap.getFrontLeftSpeed();
    	this.frontRightSpeedCon = robotMap.getFrontRightSpeed();
    	this.backRightSpeedCon = robotMap.getBackRightSpeed();
    	this.backLeftSpeedCon = robotMap.getBackLeftSpeed();
    	this.robotDrive41 = robotMap.getRobotDrive();
    	this.leftEncoder = new Encoder(0, 1, false, Encoder.EncodingType.k4X);
    	this.rightEncoder = new Encoder(2,3, false, Encoder.EncodingType.k4X);
    	
         
    }

	protected void initDefaultCommand() {
		TankDriveCommand command = new TankDriveCommand();
		this.setDefaultCommand(command);
	}
	public RobotDrive getRobotDrive(){
		return robotDrive41;
	}
	public void setSpeed(double leftSpeed, double rightSpeed){
		frontLeftSpeedCon.set(leftSpeed);
		frontRightSpeedCon.set(rightSpeed);
		backLeftSpeedCon.set(leftSpeed);
		backRightSpeedCon.set(rightSpeed);
		
	}

	
	public double getLeftEncoder(){
		return leftEncoder.getDistance();
	}
	
	public double getRightEncoder(){
		return rightEncoder.getDistance();
	}
    public void resetEncoders(){
    	leftEncoder.reset();
    	rightEncoder.reset();
    }
    
    public Encoder getRightEncoderObject(){
    	return rightEncoder;
    }
    public Encoder getLeftEncoderObject(){
    	return leftEncoder;
    }
	
 }

