package org.usfirst.frc5329.ProperRobot;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

public class RobotMapTest implements RobotMap{
	public SpeedController drivetrainFrontLeftSpeed;
    public SpeedController drivetrainBackLeftSpeed;
    public SpeedController drivetrainFrontRightSpeed;
    public SpeedController drivetrainBackRightSpeed;
    public SpeedController rollerSpeed;
    public RobotDrive drivetrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainFrontLeftSpeed = new Talon(0);
        LiveWindow.addActuator("Drive train", "frontLeft speed con", (Talon) drivetrainFrontLeftSpeed);
        
        drivetrainBackLeftSpeed = new Talon(1);
        LiveWindow.addActuator("Drive train", "backLeft speed con", (Talon) drivetrainBackLeftSpeed);
        
        drivetrainFrontRightSpeed = new Talon(2);
        LiveWindow.addActuator("Drive train", "frontRight speed con", (Talon) drivetrainFrontRightSpeed);
        
        drivetrainBackRightSpeed = new Talon(3);
        LiveWindow.addActuator("Drive train", "backRight speed con", (Talon) drivetrainBackRightSpeed);
        
        rollerSpeed = new Talon(4);
        
        drivetrainRobotDrive41 = new RobotDrive(drivetrainFrontLeftSpeed, drivetrainBackLeftSpeed,
              drivetrainFrontRightSpeed, drivetrainBackRightSpeed);
        
        drivetrainRobotDrive41.setSafetyEnabled(true);
        drivetrainRobotDrive41.setExpiration(0.1);
        drivetrainRobotDrive41.setSensitivity(0.5);
        drivetrainRobotDrive41.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

	public  SpeedController getFrontLeftSpeed() {
		return drivetrainFrontLeftSpeed;
	}

	
	public SpeedController getBackLeftSpeed() {
		return drivetrainBackLeftSpeed;
	}

	

	public SpeedController getFrontRightSpeed() {
		return drivetrainFrontRightSpeed;
	}

	
	public SpeedController getBackRightSpeed() {
		return drivetrainBackRightSpeed;
	}

	
	public RobotDrive getRobotDrive() {
		return drivetrainRobotDrive41;
	}

	@Override
	public SpeedController getRollerSpeed() {
		return rollerSpeed;
	}

}
