// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5329.ProperRobot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Spark;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMapActual implements RobotMap{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public SpeedController drivetrainFrontLeftSpeed;
    public SpeedController drivetrainBackLeftSpeed;
    public SpeedController drivetrainFrontRightSpeed;
    public SpeedController drivetrainBackRightSpeed;
    public SpeedController rollerSpeed;
    public RobotDrive drivetrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainFrontLeftSpeed = new Spark(0);
        LiveWindow.addActuator("Drive train", "frontLeft speed con", (Spark) drivetrainFrontLeftSpeed);
        
        drivetrainBackLeftSpeed = new Spark(1);
        LiveWindow.addActuator("Drive train", "backLeft speed con", (Spark) drivetrainBackLeftSpeed);
        
        drivetrainFrontRightSpeed = new Spark(2);
        LiveWindow.addActuator("Drive train", "frontRight speed con", (Spark) drivetrainFrontRightSpeed);
        
        drivetrainBackRightSpeed = new Spark(3);
        LiveWindow.addActuator("Drive train", "backRight speed con", (Spark) drivetrainBackRightSpeed);
        
        rollerSpeed = new Spark(4);
        
        
        drivetrainRobotDrive41 = new RobotDrive(drivetrainFrontLeftSpeed, drivetrainBackLeftSpeed,
              drivetrainFrontRightSpeed, drivetrainBackRightSpeed);
        
        drivetrainRobotDrive41.setSafetyEnabled(true);
        drivetrainRobotDrive41.setExpiration(0.1);
        drivetrainRobotDrive41.setSensitivity(0.5);
        drivetrainRobotDrive41.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

	public  SpeedController getFrontLeftSpeed() {
		return drivetrainFrontLeftSpeed;
	}

	
	public SpeedController getBackLeftSpeed() {
		return drivetrainBackLeftSpeed;
	}

	

	public SpeedController getFrontRightSpeed() {
		return drivetrainFrontRightSpeed;
	}

	
	public SpeedController getBackRightSpeed() {
		return drivetrainBackRightSpeed;
	}

	
	public RobotDrive getRobotDrive() {
		return drivetrainRobotDrive41;
	}

	@Override
	public SpeedController getRollerSpeed() {
		return rollerSpeed;
	}

	
    
}
